Repository pallets-eco/flask-admin, pull requests merged in 2024-07, with the labels that each got.

#2460 Replace Flask-BabelEx with Flask-Babel
  .github/workflows/tests.yaml
  README.md
  doc/advanced.rst
  examples/babel/README.rst
  examples/babel/app.py
  examples/babel/requirements.txt
  examples/sqla/admin/__init__.py
  examples/sqla/requirements.txt
  flask_admin/babel.py
  flask_admin/tests/__init__.py
  flask_admin/tests/conftest.py
  flask_admin/tests/fileadmin/__init__.py
  flask_admin/tests/fileadmin/test_fileadmin.py
  flask_admin/tests/fileadmin/test_fileadmin_azure.py
  flask_admin/tests/geoa/__init__.py
  flask_admin/tests/geoa/conftest.py
  flask_admin/tests/geoa/test_basic.py
  flask_admin/tests/mongoengine/__init__.py
  flask_admin/tests/mongoengine/conftest.py
  flask_admin/tests/mongoengine/test_basic.py
  flask_admin/tests/peeweemodel/__init__.py
  flask_admin/tests/peeweemodel/conftest.py
  flask_admin/tests/peeweemodel/test_basic.py
  flask_admin/tests/pymongo/__init__.py
  flask_admin/tests/pymongo/conftest.py
  flask_admin/tests/pymongo/test_basic.py
  flask_admin/tests/sqla/__init__.py
  flask_admin/tests/sqla/conftest.py
  flask_admin/tests/sqla/test_basic.py
  flask_admin/tests/sqla/test_form_rules.py
  flask_admin/tests/sqla/test_inlineform.py
  flask_admin/tests/sqla/test_multi_pk.py
  flask_admin/tests/sqla/test_postgres.py
  flask_admin/tests/sqla/test_translation.py
  flask_admin/tests/test_base.py
  flask_admin/tests/test_form_upload.py
  flask_admin/tests/test_model.py
  flask_admin/translations/zh_Hans_CN/LC_MESSAGES/advanced.po
  pyproject.toml
  requirements/dev.txt
  requirements/tests.in
  requirements/typing.txt
  tox.ini
Labels: breaking-change

#2321 String null fix
  flask_admin/contrib/sqla/form.py
  flask_admin/tests/sqla/test_basic.py
Labels: bug, breaking-change

#2461 Add Flask `host_matching` support to admin instances
  admin/__init__.py
  doc/advanced.rst
  examples/host-matching/README.rst
  examples/host-matching/app.py
  examples/host-matching/requirements.txt
  examples/host-matching/templates/first.html
  examples/host-matching/templates/second.html
  examples/host-matching/templates/third.html
  flask_admin/base.py
  flask_admin/blueprints.py
  flask_admin/consts.py
  flask_admin/tests/test_base.py
  flask_admin/tests/test_host_matching.py
Labels: enhancement

#2462 Pull together all Flask-Admin theme configuration
  doc/advanced.rst
  doc/introduction.rst
  examples/auth-flask-login/app.py
  examples/auth/app.py
  examples/bootstrap4/app.py
  examples/custom-layout/app.py
  examples/forms-files-images/app.py
  examples/geo_alchemy/app.py
  examples/simple/app.py
  examples/sqla-association_proxy/app.py
  examples/sqla/admin/__init__.py
  examples/sqla/admin/config.py
  examples/sqla/admin/main.py
  flask_admin/base.py
  flask_admin/form/widgets.py
  flask_admin/templates/bootstrap2/admin/base.html
  flask_admin/templates/bootstrap3/admin/base.html
  flask_admin/templates/bootstrap4/admin/base.html
  flask_admin/tests/fileadmin/test_fileadmin.py
  flask_admin/tests/test_model.py
  flask_admin/theme.py
Labels: enhancement, breaking-change, theme

#2472 Use `FLASK_ADMIN_` prefix for all `app.config` configuration
  doc/advanced.rst
  examples/geo_alchemy/README.rst
  examples/geo_alchemy/app.py
  examples/geo_alchemy/config.py
  flask_admin/contrib/sqla/view.py
  flask_admin/model/base.py
  flask_admin/static/admin/js/form.js
  flask_admin/templates/bootstrap2/admin/lib.html
  flask_admin/templates/bootstrap3/admin/lib.html
  flask_admin/templates/bootstrap4/admin/lib.html
Labels: breaking-change
